services:
  - type: web
    name: kate-have-usa-chatbot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GOOGLE_SERVICE_ACCOUNT
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_TTS_API_KEY
        sync: false
      - key: FLASK_SECRET_KEY
        generateValue: true
